name: foda
description: This is a on-demend food delivery app specifically for learning and exploring flutter amazing framework. This Project is developed to help beginners, intermediates and sometime advance to know better about using Firebase services and tools, different flutter state management solutions, complex navigations, realtime control over maps, understanding payments etc. This will help you build a strong portfolio for your journey as becoming a valuable FLUTTER DEVELOPER.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true

  # assets:
  #   - images/a_dot_burr.jpeg

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
